#!/usr/bin/env bash
# hermes-memory-decay — all-in-one installer and updater
#
# Usage:
#   bash install.sh              Fresh install (clone core, generate config)
#   bash install.sh --update     Update repos + plugin files, preserve config
#   bash install.sh --core /path  Use existing memory-decay-core at /path
#
# Designed to be copy-pasted into AI agents (Claude Code, Hermes, etc.)
# No interactive prompts — fully automatable.
#
# Environment:
#   HERMES_HOME    Override default ~/.hermes
#   GEMINI_API_KEY  Checked after install, warns if missing

set -euo pipefail

# ── Args ──────────────────────────────────────────────────────────────────
MODE="install"
CORE_OVERRIDE=""
for arg in "${1:-}" "${2:-}"; do
    case "$arg" in
        --update)    MODE="update" ;;
        --core)      shift; CORE_OVERRIDE="${1:-}" ;;
        -h|--help)
            sed -n '2,/^$/{ s/^# //; s/^#//; p }' "$0"
            exit 0 ;;
    esac
done

# ── Paths ─────────────────────────────────────────────────────────────────
HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
PLUGIN_DIR="$HERMES_HOME/plugins/hermes-memory-decay"
SKILLS_DIR="$HERMES_HOME/skills/memory-decay"
DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/hermes-memory-decay"
CORE_NAME="memory-decay-core"
CORE_REPO="https://github.com/memory-decay/memory-decay-core.git"

# ── Logging ───────────────────────────────────────────────────────────────
log()  { printf "[INFO]  %s\n" "$*"; }
warn() { printf "[WARN]  %s\n" "$*" >&2; }
err()  { printf "[ERROR] %s\n" "$*" >&2; }

# ── Detect memory-decay-core ─────────────────────────────────────────────
find_core() {
    # 1. Explicit override
    if [[ -n "$CORE_OVERRIDE" ]]; then
        if [[ -d "$CORE_OVERRIDE/src/memory_decay" ]]; then
            echo "$CORE_OVERRIDE"
            return 0
        else
            err "Specified core path does not contain src/memory_decay/: $CORE_OVERRIDE"
            exit 1
        fi
    fi

    # 2. Existing config
    if [[ -f "$PLUGIN_DIR/config.yaml" ]]; then
        local existing
        existing=$(grep '^memory_decay_path:' "$PLUGIN_DIR/config.yaml" 2>/dev/null | head -1 | sed 's/^memory_decay_path:[[:space:]]*//' || true)
        if [[ -n "$existing" ]]; then
            existing=$(eval echo "$existing")  # expand ~
            if [[ -d "$existing/src/memory_decay" ]]; then
                echo "$existing"
                return 0
            fi
        fi
    fi

    # 3. Common locations
    local search_paths=(
        "$HOME/workspace/$CORE_NAME"
        "$HOME/projects/$CORE_NAME"
        "$HOME/dev/$CORE_NAME"
        "$HOME/src/$CORE_NAME"
        "$HOME/$CORE_NAME"
        "$DATA_DIR/$CORE_NAME"
    )
    for p in "${search_paths[@]}"; do
        if [[ -d "$p/src/memory_decay" ]]; then
            echo "$p"
            return 0
        fi
    done

    return 1
}

clone_core() {
    log "Cloning memory-decay-core to $DATA_DIR/$CORE_NAME ..." >&2
    mkdir -p "$DATA_DIR"
    git clone --depth 1 "$CORE_REPO" "$DATA_DIR/$CORE_NAME" >&2 || {
        err "Failed to clone memory-decay-core"
        exit 1
    }
    if [[ ! -d "$DATA_DIR/$CORE_NAME/src/memory_decay" ]]; then
        err "Cloned repo has unexpected structure"
        exit 1
    fi
    echo "$DATA_DIR/$CORE_NAME"
}

update_core() {
    local core_path="$1"
    if [[ -d "$core_path/.git" ]]; then
        log "Updating memory-decay-core ..."
        (cd "$core_path" && git pull --ff-only 2>&1) || warn "git pull failed for core (continuing)"
    else
        warn "memory-decay-core is not a git repo ($core_path) — skipping update"
    fi
}

# ── Install core Python deps ─────────────────────────────────────────────
install_core_deps() {
    local core_path="$1"

    # Detect best python
    local py="python3"
    if [[ -f "$core_path/.venv/bin/python" ]]; then
        py="$core_path/.venv/bin/python"
    elif [[ -f "$core_path/venv/bin/python" ]]; then
        py="$core_path/venv/bin/python"
    fi

    log "Installing memory-decay-core deps ($py) ..." >&2
    (cd "$core_path" && "$py" -m pip install -e ".[server]" --quiet) || {
        warn "pip install failed — you may need to run it manually" >&2
        warn "  cd $core_path && $py -m pip install -e '.[server]'" >&2
    }

    echo "$py"
}

# ── Generate config.yaml ─────────────────────────────────────────────────
generate_config() {
    local core_path="$1"
    local py_path="$2"
    local api_key_env="${3:-GEMINI_API_KEY}"

    cat > "$PLUGIN_DIR/config.yaml" << EOF
# hermes-memory-decay — auto-generated by install.sh
# Edit freely. Reinstalling (--update) will NOT overwrite this file.

memory_decay_path: $core_path
python_path: $py_path
port: 8100
db_path: $HERMES_HOME/memory-decay/memories.db
embedding_provider: gemini
embedding_api_key_env: $api_key_env
tick_interval_seconds: 3600
auto_start_server: true
server_startup_timeout_ms: 15000
max_restarts: 3
EOF
}

# ── Main ─────────────────────────────────────────────────────────────────
main() {
    log "hermes-memory-decay $MODE"
    log "  Hermes:  $HERMES_HOME"
    log "  Repo:    $REPO_DIR"

    # Pre-flight
    if ! command -v python3 &>/dev/null; then
        err "python3 not found. Install Python 3.10+ first."
        exit 1
    fi

    if ! command -v git &>/dev/null; then
        err "git not found. Install git first."
        exit 1
    fi

    # ── Step 1: memory-decay-core ──
    core_path=""
    py_path="python3"

    if [[ "$MODE" == "update" ]]; then
        # Pull this repo
        if [[ -d "$REPO_DIR/.git" ]]; then
            log "Updating hermes-memory-decay ..."
            (cd "$REPO_DIR" && git pull --ff-only 2>&1) || warn "git pull failed for plugin repo (continuing)"
        fi
        # Update core
        core_path=$(find_core) || {
            warn "memory-decay-core not found — skipping core update"
        }
        if [[ -n "$core_path" ]]; then
            update_core "$core_path"
            py_path=$(install_core_deps "$core_path")
        fi
    else
        # Fresh install
        core_path=$(find_core 2>/dev/null) || {
            core_path=$(clone_core)
        }
        py_path=$(install_core_deps "$core_path")
    fi

    # ── Step 2: Plugin files (always overwrite) ──
    mkdir -p "$PLUGIN_DIR"
    cp "$REPO_DIR/src/hermes_memory_decay/"*.py "$PLUGIN_DIR/"
    cp "$REPO_DIR/src/hermes_memory_decay/plugin.yaml" "$PLUGIN_DIR/"
    if [[ -f "$REPO_DIR/src/hermes_memory_decay/config.yaml.example" ]]; then
        cp "$REPO_DIR/src/hermes_memory_decay/config.yaml.example" "$PLUGIN_DIR/config.yaml.example"
    fi
    log "Plugin files -> $PLUGIN_DIR"

    # ── Step 3: Config (preserve existing) ──
    if [[ -f "$PLUGIN_DIR/config.yaml" ]]; then
        log "Existing config.yaml preserved"
    elif [[ -n "$core_path" ]]; then
        generate_config "$core_path" "$py_path"
        log "Generated config.yaml (memory_decay_path=$core_path)"
    fi

    # ── Step 4: Skills (no-clobber) ──
    if [[ -d "$REPO_DIR/skills" ]]; then
        mkdir -p "$SKILLS_DIR"
        cp -rn "$REPO_DIR/skills/"* "$SKILLS_DIR/" 2>/dev/null || true
        log "Skills -> $SKILLS_DIR"
    fi

    # ── Step 5: Summary ──
    echo ""
    log "Done."
    echo ""
    echo "  Plugin:  $PLUGIN_DIR"
    echo "  Skills:  $SKILLS_DIR"
    echo "  Core:    ${core_path:-<not found>}"
    echo "  Config:  $PLUGIN_DIR/config.yaml"

    # Check API key
    local api_key_env="GEMINI_API_KEY"
    if [[ -f "$PLUGIN_DIR/config.yaml" ]]; then
        api_key_env=$(grep '^embedding_api_key_env:' "$PLUGIN_DIR/config.yaml" 2>/dev/null | head -1 | sed 's/^embedding_api_key_env:[[:space:]]*//' || echo "GEMINI_API_KEY")
    fi
    if [[ -z "${!api_key_env:-}" ]]; then
        warn "Set $api_key_env before first use:"
        warn "  export $api_key_env=your-key-here"
    else
        log "$api_key_env is set"
    fi

    echo ""
    echo "  Verify:  hermes plugins list"
    echo ""
}

main "$@"
